### ISSUE TITLE
¡Bienvenido a PdeP!

### ISSUE THREAD

**Issue by dlopezalvas** [pdepjm/2022-tp0-presentacion-AlyL00#1]
¡Hola Alyster! ¿Cómo te va?

Uuuuh el ping pong de campus, flashbacks pre-pandemia. 

¡Bienvenido a la cursada! Muchos éxitos :D

**Comment by AlysterL** [comment]
Hola Diana! Todo bieenn, cuando eramos felices y no lo sabiamos jajajjajaj

Muchas gracias! :)
